# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Movie.create(title: "Wonder Woman 1984", overview: "Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s", poster_url: "https://image.tmdb.org/t/p/original/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg", rating: 6.9)
Movie.create(title: "The Shawshank Redemption", overview: "Framed in the 1940s for double murder, upstanding banker Andy Dufresne begins a new life at the Shawshank prison", poster_url: "https://image.tmdb.org/t/p/original/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg", rating: 8.7)
Movie.create(title: "Titanic", overview: "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic.", poster_url: "https://image.tmdb.org/t/p/original/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg", rating: 7.9)
Movie.create(title: "Ocean's Eight", overview: "Debbie Ocean, a criminal mastermind, gathers a crew of female thieves to pull off the heist of the century.", poster_url: "https://image.tmdb.org/t/p/original/MvYpKlpFukTivnlBhizGbkAe3v.jpg", rating: 7.0)
Movie.create(title: "Spider-Man: No Way Home", overview: "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.", poster_url: "https://www.themoviedb.org/t/p/original/zAEV3KFOKgITIvl8dSS9yiWsApF.jpg", rating: 9.0)
Movie.create(title: "The Matrix Resurrections", overview: "Plagued by strange memories, Neo's life takes an unexpected turn when he finds himself back inside the Matrix.", poster_url: "https://www.themoviedb.org/t/p/original/8c4a8kE7PizaGQQnditMmI1xbRp.jpg", rating: 6.5)
Movie.create(title: "Inception", overview: "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: inception, the implantation of another person's idea into a target's subconscious.", poster_url: "https://www.themoviedb.org/t/p/original/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg", rating: 10.0)
Movie.create(title: "Acclimatising: Our time on Earth at Barbican Centre", overview: "A major exhibition in multiple spaces across the Barbican Centre includes futuristic installations, grassroots activism and learning from indigenous communities to discover how we live in a more harmonious way with nature, making Earth more habitable for us and other species. 5 May-29 August 2022", poster_url: "https://assets.londonist.com/uploads/2021/12/i730/11-_space10_-_the_ideal_city_-_p-19_-_photo_by_iwan_baan_-_gestalten_2021-web.jpg")
Movie.create(title: "Van Gogh Self Portraits at Courtauld Gallery", overview: "The newly-refurbished Courtauld Gallery is rectifying this with a show of 15 self-portraits, charting his life from his early days to his latter years in an asylum — with intense stares aplenty.", poster_url: "https://assets.londonist.com/uploads/2021/12/i730/d07b3a5df7178acb410f0adcaedd2da3b03b66ad-1227x1600.jpg")
Movie.create(title: "Spider and silk - Louise Bourgeois at Hayward Gallery", overview: "Hayward Gallery is filling that gap with a show dedicated to her textile works that use everyday domestic items like bed linen and napkins, which she uses to cover the themes of identity and sexuality, trauma and memory, guilt and reparation that are central to her long career.", poster_url: "https://assets.londonist.com/uploads/2021/12/i730/dynamic-2c849d3b-6f55-5be9-bceb-26efcef56194.jpg")
Movie.create(title: "Parsons at Covent Garden", overview: "Great wine (obvs) but cracking seafood too. It’s a dinky space, like a cross between a fishmonger and a wine bar", poster_url: "https://media.timeout.com/images/105210463/1372/1029/image.jpg", rating: 8)
Movie.create(title: "Santo Remedio at London Bridge", overview: "The born-again-version of the Mexican restaurant, now moved from Shoreditch to south of the river (opposite the Unicorn Theatre on Borough’s Tooley St), is an absolute slam-dunk.", poster_url: "https://media.timeout.com/images/105160016/1372/1029/image.jpg", rating: 8)
Movie.create(title: "Palomar at China Town", overview: "Everything off the ‘raw’ (more accurately: ‘cold’) bar is terrific, such as the beautiful beetroot carpaccio with burnt goat’s cheese, hazelnut brittle and a drizzle of pomegranate molasses vinaigrette.", poster_url: "https://media.timeout.com/images/103462716/1372/1029/image.jpg", rating: 7)
Movie.create(title: "Trullo at Highbury", overview: "The pappardelle with beef shin ragù is so famous it has had its own Twitter account – and so popular it made the leap on to the menu at sister restaurant Padella.", poster_url: "https://media.timeout.com/images/63345/1372/1029/image.jpg", rating: 9)
puts "Movies created"
